version: '3.9'

services:
  splunkuniversalforwarder:
    hostname: splunkuniversalforwarder
    #image: splunk/universalforwarder:8.2.5
    image: splunk/splunk:8.2.6
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_PASSWORD=kong@2022
    volumes:
      - ./opt-splunk-etc:/opt/splunk/etc
      - ./opt-splunk-var:/opt/splunk/var
    ports:
      - "8000:8000"
      - "9997:9997"
      - "8088:8088"
      - "1514:1514"
      - "9200:9200"
