version: '3.9'

services:
  opensearch_exporter:
    image: bitnami/elasticsearch-exporter:1.3.0
    command:
     - '--es.uri=https://admin:admin@10.130.0.2:9200'
     - '--es.ssl-skip-verify'
    restart: always
    network_mode: host
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"
