version: '3.9'
services:
  cassandra-exporter:
    image: criteord/cassandra_exporter:2.3.8
    restart: always
    network_mode: host
    
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"
